services:
  unifi-db:
    image: mongo:7.0
    container_name: unifi-db
    restart: unless-stopped
    env_file:
      - ./unifi.env
    volumes:
      - data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: unless-stopped
    depends_on:
      unifi-db:
        condition: service_healthy
    env_file:
      - ./unifi.env
    volumes:
      - config:/config
    networks:
      - unifi
      - backend
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional

networks:
  backend:
  unifi:
    driver: bridge

volumes:
  data:
  config:
